const PAGES = {
  ROOT: '/autismedu',
  HOME: '/',
  LOGIN: '/login',
  DASHBOARD: '/admin/dashboard',
  USERMANAGEMENT: '/admin/user-management',
  ROLECLAIMMANAGEMENT: '/admin/role-claim-management',
  FORGOTPASSWORD: '/forgot-password',
  REGISTER: '/register',
  RESETPASSWORD: '/reset-password',
  CONFIRMREGISTER: '/confirm-register',
  LISTCENTER: '/list-center',
  CENTERPROFILE: '/center/:id',
  LISTTUTOR: '/list-tutor',
  TUTORPROFILE: '/tutor-profile/:id',
  TUTORPROFILEUPDATE: '/tutor-profile-update/:id',
  TUTORREGISTRATIONMANAGEMENT: '/admin/tutor-registration-management',
  TUTORREGISTRATION: '/autismtutor/tutor-registration',
  MY_STUDENT: '/autismtutor/my-student',
  STUDENT_DETAIL: '/autismtutor/student-detail/:id',
  TUTOR_SETTING: '/autismtutor/tutor-setting',
  LOGIN_OPTION: '/login-option',
  TUTOR_LOGIN: '/autismtutor/tutor-login',
  TUTOR_REQUEST: '/autismtutor/tutor-request',
  REGISTER_OPTION: '/register-option',
  MY_CHILDREN: '/my-childlren',
  CALENDAR: '/autismtutor/calendar',
  PARENT_PROFILE: '/my-profile',
  CHANGE_PASSWORD: '/change-password',
  ASSESSMENT_MANAGEMENT: '/admin/assessment-management',
  ASSESSMENT_CREATION: '/admin/assessment-creation',
  CERTIFICATE_DETAIL: '/autismtutor/certificate-detail/:id',
  STUDENT_CREATION: '/autismtutor/create-student-profile',
  APPROVE_STUDENT_PROFILE: '/approve-student-profile/:id'
};

export default PAGES;